<?php
declare(strict_types=1);

$nombre = (string) ($usuario['nombre'] ?? 'Usuario');
$usuarioId = (int) ($usuario['sub'] ?? 0);
$db = \App\Facturacion\Config\Database::getConnection();
$empresas = (new \App\Facturacion\Repositories\EmpresaFacturacionRepository($db))->findByUsuarioId($usuarioId);
$empresas = array_values(array_filter($empresas, static fn ($empresa): bool => $empresa->activo));
$e = static fn (?string $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$cssPath = dirname(__DIR__, 2) . '/public/assets/css/landing.css';
$cssVersion = is_file($cssPath) ? (string) filemtime($cssPath) : '1';
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nueva venta · Panel SUNAT</title>
    <script>(()=>{const s=localStorage.getItem('landing-theme'),d=s?s==='dark':matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.classList.toggle('dark',d)})()</script>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/public/assets/css/landing.css?v=<?= $cssVersion ?>">
</head>
<body class="min-h-screen overflow-x-hidden bg-[#f4f6f8] text-[#182230] antialiased dark:bg-[#0b0d10] dark:text-[#edf0f3]" style="font-family:'IBM Plex Sans',sans-serif">
    <header class="border-b border-slate-200 bg-white dark:border-white/10 dark:bg-[#111419]">
        <div class="mx-auto flex h-16 max-w-[1440px] items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-8"><a href="/dashboard" class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-md bg-[#182230] text-xs font-bold text-signal dark:bg-signal dark:text-black">CM</span><span class="hidden sm:block"><strong class="block text-sm font-bold">Panel SUNAT</strong><small class="text-xs text-slate-500 dark:text-slate-400">Facturador interno</small></span></a><nav class="hidden items-center gap-1 md:flex"><a href="/dashboard" class="admin-nav-link">Empresas</a><?php if (($usuario['rol'] ?? '') === 'admin'): ?><a href="/usuarios" class="admin-nav-link">Usuarios</a><?php endif; ?><a href="/productos" class="admin-nav-link">Productos</a><a href="/vender" class="admin-nav-link admin-nav-active">Vender</a><a href="/ventas" class="admin-nav-link">Ventas</a></nav></div><div class="flex items-center gap-2"><span class="hidden text-sm text-slate-500 sm:inline dark:text-slate-400"><?= $e($nombre) ?></span><button id="theme-toggle" class="admin-icon-button" type="button" aria-label="Cambiar tema">◐</button><a href="/logout" class="admin-icon-button" aria-label="Cerrar sesión">↗</a></div></div>
        <nav class="flex overflow-x-auto border-t border-slate-100 px-2 md:hidden dark:border-white/5"><a href="/dashboard" class="admin-mobile-link">Empresas</a><a href="/productos" class="admin-mobile-link">Productos</a><a href="/vender" class="admin-mobile-link border-b-2 border-[#9aac00] text-[#657500] dark:border-signal dark:text-signal">Vender</a><a href="/ventas" class="admin-mobile-link">Ventas</a></nav>
    </header>

    <main class="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8">
        <div><p class="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500 dark:text-slate-400">Caja rápida</p><h1 class="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Nueva venta</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Crea, envía a SUNAT e imprime el comprobante sin administrar inventario.</p></div>
        <?php if (!$empresas): ?><section class="mt-7 rounded-lg border border-slate-200 bg-white p-10 text-center shadow-sm dark:border-white/10 dark:bg-[#111419]"><h2 class="text-lg font-bold">No hay una empresa activa vinculada</h2><p class="mt-2 text-sm text-slate-500">Activa o vincula una empresa a tu usuario antes de vender.</p></section><?php else: ?>
        <div class="mt-7 grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
            <div class="min-w-0 space-y-6">
                <section class="min-w-0 rounded-lg border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#111419]"><div class="border-b border-slate-200 px-4 py-4 dark:border-white/10 sm:px-5"><span class="pos-step">01</span><h2 class="inline text-sm font-semibold">Comprobante</h2></div><div class="grid min-w-0 gap-4 p-4 sm:p-5 md:grid-cols-3"><label class="min-w-0"><span class="field-label">Empresa</span><select id="empresa" class="field-input"><?php foreach ($empresas as $empresa): ?><option value="<?= $empresa->id ?>"><?= $e($empresa->nombreComercial ?: $empresa->razonSocial) ?> · <?= $e($empresa->ruc) ?></option><?php endforeach; ?></select></label><label class="min-w-0"><span class="field-label">Tipo</span><select id="tipoComprobante" class="field-input"><option value="03">Boleta de venta</option><option value="01">Factura</option></select></label><label class="min-w-0"><span class="field-label">Serie</span><select id="serie" class="field-input" required><option value="">Cargando series…</option></select></label></div></section>

                <section class="min-w-0 rounded-lg border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#111419]"><div class="border-b border-slate-200 px-4 py-4 dark:border-white/10 sm:px-5"><span class="pos-step">02</span><h2 class="inline text-sm font-semibold">Cliente</h2><p class="mt-1 text-xs text-slate-500">La consulta es opcional; todos los datos permanecen editables.</p></div><div class="grid min-w-0 gap-4 p-4 sm:p-5 md:grid-cols-2"><label class="min-w-0"><span class="field-label">Documento</span><select id="tipoDocumento" class="field-input"><option value="1">DNI</option><option value="6">RUC</option></select></label><label class="min-w-0"><span class="field-label">Número</span><div class="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input id="numeroDocumento" class="field-input min-w-0" inputmode="numeric" maxlength="8" placeholder="12345678"><button type="button" id="buscarDocumento" class="admin-secondary-button w-full sm:w-auto">Buscar</button></div></label><label class="min-w-0"><span class="field-label">Nombres o razón social</span><input id="clienteNombre" class="field-input" required placeholder="Puedes escribirlo manualmente"></label><label class="min-w-0"><span class="field-label">Dirección</span><input id="clienteDireccion" class="field-input" placeholder="Opcional"></label><div id="documentoAlert" class="form-alert hidden min-w-0 break-words md:col-span-2"></div></div></section>

                <section class="min-w-0 rounded-lg border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#111419]"><div class="border-b border-slate-200 px-4 py-4 dark:border-white/10 sm:px-5"><span class="pos-step">03</span><h2 class="inline text-sm font-semibold">Detalle de venta</h2><p class="mt-1 text-xs text-slate-500">Busca por código o nombre. El selector carga 10 resultados por página.</p></div><div class="min-w-0 p-4 sm:p-5"><div class="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label class="min-w-0"><span class="field-label">Producto o servicio</span><select id="productoSelect" class="w-full max-w-full"></select></label><button type="button" id="agregarProducto" class="admin-primary-button w-full self-end sm:w-auto">Agregar</button></div><div class="mt-5 max-w-full overflow-x-auto overscroll-x-contain"><table class="w-full min-w-[650px] border-collapse"><thead><tr class="border-b border-slate-200 text-left text-[11px] uppercase tracking-wider text-slate-500 dark:border-white/10"><th class="px-2 py-3">Producto</th><th class="px-2 py-3 w-24">Cantidad</th><th class="px-2 py-3 w-32">Precio</th><th class="px-2 py-3 text-right">Importe</th><th class="w-10"></th></tr></thead><tbody id="detalleBody"><tr id="emptyRow"><td colspan="5" class="py-10 text-center text-sm text-slate-400">Agrega el primer producto para iniciar la venta.</td></tr></tbody></table></div></div></section>
            </div>

            <aside class="h-fit min-w-0 rounded-lg border border-slate-200 bg-white shadow-sm xl:sticky xl:top-6 dark:border-white/10 dark:bg-[#111419]"><div class="border-b border-slate-200 p-4 dark:border-white/10 sm:p-5"><p class="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Resumen</p><h2 class="mt-1 text-xl font-bold">Total de venta</h2></div><div class="min-w-0 space-y-3 p-4 text-sm sm:p-5"><div class="flex min-w-0 justify-between gap-3 text-slate-500"><span>Valor de venta</span><strong id="subtotal" class="shrink-0 text-[#182230] dark:text-white">S/ 0.00</strong></div><div class="flex min-w-0 justify-between gap-3 text-slate-500"><span>IGV</span><strong id="igv" class="shrink-0 text-[#182230] dark:text-white">S/ 0.00</strong></div><div class="mt-4 flex min-w-0 items-end justify-between gap-3 border-t border-slate-200 pt-5 dark:border-white/10"><span class="font-semibold">Total</span><strong id="total" class="min-w-0 break-all text-right text-3xl tracking-tight">S/ 0.00</strong></div><label class="block min-w-0 pt-3"><span class="field-label">Moneda</span><select id="moneda" class="field-input"><option value="PEN">Soles · PEN</option><option value="USD">Dólares · USD</option></select></label><label class="block min-w-0"><span class="field-label">Formato de impresión</span><select id="formato" class="field-input"><option value="ticket">Ticket 80 mm</option><option value="a4">A4</option></select></label><div id="saleAlert" class="form-alert hidden min-w-0 break-words"></div><button type="button" id="confirmarVenta" class="admin-primary-button mt-3 w-full !py-3">Emitir comprobante</button><p class="text-center text-[11px] leading-5 text-slate-400">La venta se procesa sin abrir el PDF. Al finalizar podrás imprimirlo o compartirlo.</p></div></aside>
        </div><?php endif; ?>
    </main>

    <div id="confirmModal" class="app-modal" role="dialog" aria-modal="true"><div class="modal-panel max-w-lg"><div class="modal-heading"><div><p class="modal-kicker">Confirmar operación</p><h2 class="modal-title">¿Seguro que quieres realizar la venta?</h2><p class="mt-2 text-sm leading-6 text-slate-500">Se reservará un correlativo y el comprobante será enviado a SUNAT.</p></div><button type="button" data-close-confirm class="modal-close">×</button></div><div id="confirmSummary" class="mt-6 rounded-md bg-slate-50 p-4 text-sm dark:bg-white/5"></div><div class="modal-actions"><button type="button" data-close-confirm class="admin-secondary-button">No, revisar</button><button type="button" id="ejecutarVenta" class="admin-primary-button">Sí, emitir</button></div></div></div>

    <div id="saleSuccessModal" class="app-modal" role="dialog" aria-modal="true"><div class="modal-panel max-w-lg text-center"><div class="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#eaff00] text-3xl font-bold text-black">✓</div><p class="modal-kicker mt-6">Operación completada</p><h2 class="modal-title">Comprobante emitido</h2><p id="successSaleNumber" class="mt-2 font-mono text-sm font-bold"></p><p class="mt-3 text-sm leading-6 text-slate-500">El PDF permanece protegido. Solo se carga en memoria cuando eliges imprimir o compartir.</p><div id="successAlert" class="form-alert mt-5 hidden"></div><div class="mt-7 grid gap-3 sm:grid-cols-3"><button type="button" id="closeSuccess" class="admin-secondary-button">Cerrar</button><button type="button" id="shareSuccess" class="admin-secondary-button">Compartir</button><button type="button" id="printSuccess" class="admin-primary-button">Imprimir</button></div></div></div>

    <div id="saleLoader" class="sale-loader hidden" aria-live="assertive"><div class="sale-loader-card"><span class="sale-spinner"></span><strong id="saleLoaderTitle">Emitiendo comprobante…</strong><p>No cierres esta ventana. Estamos comunicándonos con SUNAT.</p></div></div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
    const cart=[],money=new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}),empresa=document.getElementById('empresa'),tipo=document.getElementById('tipoComprobante'),serie=document.getElementById('serie'),docType=document.getElementById('tipoDocumento'),docNumber=document.getElementById('numeroDocumento'),clientName=document.getElementById('clienteNombre'),clientAddress=document.getElementById('clienteDireccion');
    document.getElementById('theme-toggle')?.addEventListener('click',()=>{const d=!document.documentElement.classList.contains('dark');document.documentElement.classList.toggle('dark',d);localStorage.setItem('landing-theme',d?'dark':'light')});
    const setMessage=(id,state,msg)=>{const el=document.getElementById(id);el.dataset.state=state;el.textContent=msg;el.classList.remove('hidden')};
    async function fetchJson(url,options={},timeout=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{...options,signal:controller.signal,headers:{Accept:'application/json',...(options.headers||{})}}),json=await response.json();if(!response.ok||!json.success)throw new Error(json.error?.message||'La operación no pudo completarse.');return json.data}finally{clearTimeout(timer)}}
    async function loadSeries(){serie.innerHTML='<option value="">Cargando series…</option>';try{const rows=await fetchJson(`/api/facturacion/pos/series?empresa_id=${empresa.value}`),filtered=rows.filter(row=>row.tipo_comprobante===tipo.value);serie.innerHTML=filtered.length?filtered.map(row=>`<option value="${escapeHtml(row.serie)}">${escapeHtml(row.serie)} · siguiente ${String(Number(row.correlativo)+1).padStart(8,'0')}</option>`).join(''):'<option value="">Sin serie configurada</option>'}catch(e){serie.innerHTML='<option value="">No se pudieron cargar</option>';setMessage('saleAlert','error',e.message)}}
    empresa?.addEventListener('change',()=>{cart.splice(0);drawCart();loadSeries();resetProductSelect()});tipo?.addEventListener('change',()=>{docType.value=tipo.value==='01'?'6':'1';syncDocument();loadSeries()});docType?.addEventListener('change',syncDocument);function syncDocument(){docNumber.value='';docNumber.maxLength=docType.value==='6'?11:8;docNumber.placeholder=docType.value==='6'?'20123456789':'12345678';clientName.value='';clientAddress.value=''}
    function resetProductSelect(){if(!window.jQuery)return;$('#productoSelect').val(null).trigger('change')}
    if(window.jQuery&&$.fn.select2){$('#productoSelect').select2({placeholder:'Escribe un código o nombre…',minimumInputLength:0,width:'100%',ajax:{url:'/api/facturacion/pos/productos',dataType:'json',delay:250,data:params=>({empresa_id:empresa.value,q:params.term||'',page:params.page||1}),processResults:response=>response.data,cache:true},templateResult:item=>item.loading?item.text:$(`<div><strong>${$('<span>').text(item.codigo).html()}</strong><span class="block text-xs text-slate-500">${$('<span>').text(item.descripcion).html()} · S/ ${money.format(item.precio_unitario)}</span></div>`),escapeMarkup:markup=>markup})}
    document.getElementById('agregarProducto')?.addEventListener('click',()=>{const item=$('#productoSelect').select2('data')[0];if(!item||!item.id)return;const existing=cart.find(row=>String(row.id)===String(item.id));if(existing)existing.cantidad+=1;else cart.push({...item,cantidad:1,precio_unitario:Number(item.precio_unitario)});resetProductSelect();drawCart()});
    function drawCart(){const body=document.getElementById('detalleBody');body.innerHTML='';if(!cart.length){body.innerHTML='<tr><td colspan="5" class="py-10 text-center text-sm text-slate-400">Agrega el primer producto para iniciar la venta.</td></tr>'}cart.forEach((item,index)=>{const row=document.createElement('tr');row.className='border-b border-slate-100 dark:border-white/5';row.innerHTML=`<td class="px-2 py-3"><strong class="block text-sm">${escapeHtml(item.descripcion)}</strong><code class="text-xs text-slate-400">${escapeHtml(item.codigo)} · ${escapeHtml(item.unidad)}</code></td><td class="px-2 py-3"><input class="field-input !px-2 !py-2" type="number" min="0.001" step="0.001" value="${item.cantidad}" data-qty="${index}"></td><td class="px-2 py-3"><input class="field-input !px-2 !py-2" type="number" min="0" step="0.01" value="${item.precio_unitario.toFixed(2)}" data-price="${index}"></td><td class="px-2 py-3 text-right font-semibold">${money.format(item.cantidad*item.precio_unitario)}</td><td><button type="button" class="text-lg text-red-500" data-remove="${index}" aria-label="Quitar">×</button></td>`;body.appendChild(row)});body.querySelectorAll('[data-qty]').forEach(input=>input.addEventListener('change',()=>{cart[input.dataset.qty].cantidad=Math.max(.001,Number(input.value)||1);drawCart()}));body.querySelectorAll('[data-price]').forEach(input=>input.addEventListener('change',()=>{cart[input.dataset.price].precio_unitario=Math.max(0,Number(input.value)||0);drawCart()}));body.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{cart.splice(button.dataset.remove,1);drawCart()}));calculateTotals()}
    function calculateTotals(){let subtotal=0,igv=0,total=0;cart.forEach(item=>{const amount=item.cantidad*item.precio_unitario;total+=amount;if(['10','21'].includes(item.afectacion_igv)){const base=amount/1.18;subtotal+=base;igv+=amount-base}else subtotal+=amount});document.getElementById('subtotal').textContent=`S/ ${money.format(subtotal)}`;document.getElementById('igv').textContent=`S/ ${money.format(igv)}`;document.getElementById('total').textContent=`S/ ${money.format(total)}`;return total}
    const escapeHtml=value=>{const div=document.createElement('div');div.textContent=value??'';return div.innerHTML};
    document.getElementById('buscarDocumento')?.addEventListener('click',async()=>{const number=docNumber.value.trim(),kind=docType.value==='6'?'ruc':'dni',length=kind==='ruc'?11:8;if(!new RegExp(`^\\d{${length}}$`).test(number)){setMessage('documentoAlert','error',`${kind.toUpperCase()} debe tener ${length} dígitos.`);return}setMessage('documentoAlert','loading','Consultando documento…');try{const data=await fetchJson(`/api/facturacion/pos/documentos/${kind}/${number}`);clientName.value=data.nombre||clientName.value;clientAddress.value=data.direccion||clientAddress.value;setMessage('documentoAlert','success','Datos encontrados. Puedes corregirlos manualmente antes de emitir.')}catch(e){setMessage('documentoAlert','error',`${e.name==='AbortError'?'La consulta excedió el tiempo de espera.':e.message} Puedes completar los datos manualmente.`)}});
    const modal=document.getElementById('confirmModal');document.querySelectorAll('[data-close-confirm]').forEach(button=>button.addEventListener('click',()=>{modal.classList.remove('flex');document.body.style.overflow=''}));
    document.getElementById('confirmarVenta')?.addEventListener('click',()=>{if(!serie.value){setMessage('saleAlert','error','Configura y selecciona una serie.');return}const length=docType.value==='6'?11:8;if(!new RegExp(`^\\d{${length}}$`).test(docNumber.value.trim())){setMessage('saleAlert','error',`El documento debe tener ${length} dígitos.`);return}if(!clientName.value.trim()){setMessage('saleAlert','error','Ingresa los nombres o razón social del cliente.');return}if(!cart.length){setMessage('saleAlert','error','Agrega al menos un producto.');return}document.getElementById('confirmSummary').innerHTML=`<div class="flex justify-between"><span>Cliente</span><strong class="text-right">${escapeHtml(clientName.value)}</strong></div><div class="mt-2 flex justify-between"><span>Comprobante</span><strong>${tipo.options[tipo.selectedIndex].text} · ${escapeHtml(serie.value)}</strong></div><div class="mt-2 flex justify-between"><span>Total</span><strong>S/ ${money.format(calculateTotals())}</strong></div>`;modal.classList.add('flex');document.body.style.overflow='hidden'});
    let completedSale=null,completedPdfCache={};
    const successModal=document.getElementById('saleSuccessModal');
    function toggleSaleLoader(show,title='Emitiendo comprobante…'){document.getElementById('saleLoaderTitle').textContent=title;document.getElementById('saleLoader').classList.toggle('hidden',!show);document.body.classList.toggle('overflow-hidden',show);if(!show)document.body.style.overflow=''}
    document.getElementById('ejecutarVenta')?.addEventListener('click',async()=>{const button=document.getElementById('ejecutarVenta');button.disabled=true;button.textContent='Procesando…';const payload={empresa_id:Number(empresa.value),tipo_comprobante:tipo.value,serie:serie.value,moneda:document.getElementById('moneda').value,cliente:{tipo_documento:docType.value,numero_documento:docNumber.value.trim(),nombre:clientName.value.trim(),direccion:clientAddress.value.trim()},items:cart.map(item=>({codigo:item.codigo,descripcion:item.descripcion,unidad:item.unidad,cantidad:item.cantidad,precio_unitario:item.precio_unitario,afectacion_igv:item.afectacion_igv}))};let createdId=null;modal.classList.remove('flex');toggleSaleLoader(true,'Creando comprobante…');try{const created=await fetchJson('/api/facturacion/pos/comprobantes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},30000);createdId=created.id;toggleSaleLoader(true,`Enviando ${created.numero} a SUNAT…`);const processed=await fetchJson(`/api/facturacion/pos/comprobantes/${created.id}/procesar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:Number(empresa.value)})},130000);completedSale={...processed,empresa_id:Number(empresa.value),formato:document.getElementById('formato').value};completedPdfCache={};toggleSaleLoader(true,'Protegiendo PDF en memoria…');try{completedPdfCache.a4=await getCompletedPdf('a4');if(completedSale.formato!=='a4')completedPdfCache[completedSale.formato]=await getCompletedPdf(completedSale.formato)}catch(_){}toggleSaleLoader(false);document.getElementById('successSaleNumber').textContent=`${processed.numero} · ${processed.estado}`;document.getElementById('successAlert').classList.add('hidden');successModal.classList.add('flex');document.body.style.overflow='hidden';cart.splice(0);drawCart();clientName.value='';clientAddress.value='';docNumber.value='';await loadSeries()}catch(e){toggleSaleLoader(false);const timedOut=e.name==='AbortError';setMessage('saleAlert','error',timedOut&&createdId?`El envío excedió el tiempo de espera. El comprobante quedó creado con ID ${createdId}; no vuelvas a emitirlo hasta revisar su estado.`:(timedOut?'La operación excedió el tiempo de espera. Intenta nuevamente.':e.message))}finally{button.disabled=false;button.textContent='Sí, emitir'}});
    function successMessage(state,message){const el=document.getElementById('successAlert');el.dataset.state=state;el.textContent=message;el.classList.remove('hidden')}
    async function getCompletedPdf(format){if(completedPdfCache[format])return completedPdfCache[format];if(!completedSale)throw new Error('No hay un comprobante disponible.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(`${completedSale.print_url}&formato=${format}`,{signal:controller.signal});if(!response.ok){let message='PDF no disponible.';try{message=(await response.json()).error?.message||message}catch(_){}throw new Error(message)}const blob=await response.blob();completedPdfCache[format]=blob;return blob}finally{clearTimeout(timer)}}
    async function printCompleted(){const popup=window.open('','impresion-comprobante','popup=yes,width=430,height=720,toolbar=no,location=no,menubar=no,status=no,resizable=yes,scrollbars=no');if(!popup){successMessage('error','El navegador bloqueó la ventana de impresión. Habilita ventanas emergentes e inténtalo nuevamente.');return}popup.document.write('<title>Preparando impresión</title><body style="font-family:sans-serif;display:grid;place-items:center;height:90vh">Preparando impresión…</body>');toggleSaleLoader(true,'Preparando impresión…');try{const blob=await getCompletedPdf(completedSale.formato),url=URL.createObjectURL(blob);popup.location.replace(url);setTimeout(()=>{try{popup.focus();popup.print()}finally{setTimeout(()=>URL.revokeObjectURL(url),60000)}},1200)}catch(error){popup.close();successMessage('error',error.name==='AbortError'?'La descarga del PDF excedió el tiempo de espera.':error.message)}finally{toggleSaleLoader(false);document.body.style.overflow='hidden'}}
    async function shareCompleted(){toggleSaleLoader(true,'Preparando archivo para compartir…');try{const blob=await getCompletedPdf('a4'),file=new File([blob],`${completedSale.numero}.pdf`,{type:'application/pdf'});if(!navigator.share||!navigator.canShare?.({files:[file]}))throw new Error('Este navegador no permite compartir archivos. Usa un celular compatible.');await navigator.share({files:[file],title:`Comprobante ${completedSale.numero}`,text:'Comprobante electrónico'});successMessage('success','PDF compartido correctamente.')}catch(error){if(error.name==='AbortError')successMessage('error','La descarga del PDF excedió el tiempo de espera.');else if(error.name!=='NotAllowedError')successMessage('error',error.message)}finally{toggleSaleLoader(false);document.body.style.overflow='hidden'}}
    document.getElementById('printSuccess').addEventListener('click',printCompleted);document.getElementById('shareSuccess').addEventListener('click',shareCompleted);document.getElementById('closeSuccess').addEventListener('click',()=>{successModal.classList.remove('flex');document.body.style.overflow=''});
    if(empresa){loadSeries();syncDocument();drawCart()}
    </script>
</body></html>
